name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: eu-central-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # --------------------------------------------------
      # 1. Terraform Plan
      # --------------------------------------------------
      - name: Terraform Plan
        run: |
          mkdir -p plans
          terraform plan \
            -out="plans/${{ github.sha }}.tfplan"

      # --------------------------------------------------
      # 2. Convert Terraform Plan to JSON
      # --------------------------------------------------
      - name: Terraform Plan JSON
        if: github.event_name == 'pull_request'
        run: |
          terraform show \
            -json \
            "plans/${{ github.sha }}.tfplan" \
            > "plans/${{ github.sha }}.json"

      # --------------------------------------------------
      # 4. Checkov Terraform Plan Scan
      # --------------------------------------------------
      - name: Checkov Terraform Plan Scan
        if: github.event_name == 'pull_request'
        uses: bridgecrewio/checkov-action@master
        with:
         file: plans/${{ github.sha }}.json
         framework: terraform_plan
         severity: HIGH,CRITICAL
         output_format: cli
         quiet: true 
         skip_check: CKV2_AWS_41

      # --------------------------------------------------
      # 5. Upload Terraform plan after merge to main
      # --------------------------------------------------
      - name: Upload Terraform Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: plans/${{ github.sha }}.tfplan

      # --------------------------------------------------
      # 6. Apply the exact Terraform plan generated on main
      # --------------------------------------------------
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "plans/${{ github.sha }}.tfplan"